/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Profile {
    username?: string
    avatar?: string
    description?: string
    banner?: string
    links?: {
        key?: string
        value?: string
        [k: string]: unknown
    }[]
}
